### ISSUE TITLE
Error thrown when creating an online game

### ISSUE THREAD

**Issue by patchesyar** [ColonelThirtyTwo/RIT-SW-Testing-Project#3]
When I open the create game menu from the play online menu on a fresh install of this game on my windows machine, an error is immediately thrown. Even if I close the error and the create game menu, the error continues to pop back up.

OUT: WARNING: Resource not found: /locale-en-US.properties
OUT: WARNING: Resource not found: /locale-en.properties
OUT: initializer found for media.MediaInitializer: class org.me4se.psi.java1.media.MediaInitializer
OUT: initializer found for rms.RecordStoreInitializer: class org.me4se.psi.j2se.rms.RecordStoreInitializer

**Comment by ColonelThirtyTwo** [comment]
I think this is an older version of the game, so it might be due to protocol differences. Though the error messages don't seem to reinforce this.
